import * as React from "react";
const { useState, useEffect } = React;
// import useKeyPress from '../custom-hooks/useKeyPress'
import OkrTree from "../okr-tree/index.jsx";
import * as ReactDOM from "react-dom";

function App() {
  const [listData, setListData] = useState([
    {
      id: 559,
      time_cycle_id: 5,
      name: "O1:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
      department: "驭势科技",
      status: "unconsidered",
      status_info: "",
      progress: 56,
      score: 0,
      score_info: "",
      comments: "",
      parent_id: 0,
      author_id: 607,
      o_type: 2,
      is_publish: 1,
      is_delete: 0,
      is_hidden: 0,
      start_time: "2021-01-01 00:00:00",
      end_time: "2021-12-31 00:00:00",
      OwnerId: 10001,
      weightSum: 100,
      Username: "吴甘沙",
      owners: [
        {
          id: 10001,
          name: "吴甘沙",
        },
      ],
      visitors: null,
      keyResults: [
        {
          id: 1206,
          okr_id: 559,
          type: 0,
          relation_milestone_id: 0,
          name: "O1-KA1-业务布局和营收：全力开拓市场、2季度营收达标基础上确保全年2亿营收的可达性",
          result:
            "1. 冲击营收认列目标。2. 以鄂州、乌鲁木齐、天津机场拓展为基础，与民航建立初步标准框架；努力提升HKIA对我们的信任感，启动OOG项目。3. 保证15+KA的顺利进展及合资合作等拓展战略。4. 至少一个地方政府合作布局进入实质性阶段。 5. 市场推广积累2000条客户线索 。",
          status: "hard",
          status_info:
            " 天津机场进入测试标招标阶段，民航标准第一版提交，乌鲁木齐民航进展顺利，市场推广延后至8月。 民航合资启动、KA战略需要调整。 成都、佛山签署意向协议，5. Q2参加了全球物流技术、整车物流、制造业物流、汽车零部件物流等重要行业大会，累计获得2487条客户名录，627条深度客户线索。累计声量第七名",
          progress: 50,
          score: 0,
          score_info: "",
          comments: "",
          start_time: "2021-04-01 00:00:00",
          end_time: "2021-06-30 00:00:00",
          weight: 40,
          author_id: 607,
          is_delete: 0,
          OwnerId: 10105,
          Username: "邱巍",
          owners: [
            {
              id: 10105,
              name: "邱巍",
            },
            {
              id: 10003,
              name: "彭进展",
            },
          ],
          tasks: null,
          stutusInfoHistories: [
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-07-10 21:27:04",
              value:
                " 天津机场进入测试标招标阶段，民航标准第一版提交，乌鲁木齐民航进展顺利，市场推广延后至8月。 民航合资启动、KA战略需要调整。 成都、佛山签署意向协议，5. Q2参加了全球物流技术、整车物流、制造业物流、汽车零部件物流等重要行业大会，累计获得2487条客户名录，627条深度客户线索。累计声量第七名",
              jd_id: 12094,
              old_value:
                " 天津机场进入测试标招标阶段，民航标准第一版提交，乌鲁木齐民航进展顺利，市场推广延后至8月，3. 民航合资启动、KA战略需要调整，4. 成都、佛山签署意向协议，5. Q2参加了全球物流技术、整车物流、制造业物流、汽车零部件物流等重要行业大会，累计获得2487条客户名录，627条深度客户线索。累计声量第七名",
              prop_key: "status_info",
              username: "闫颂秋",
              avatar:
                "https://s1-imfile.feishucdn.com/static-resource/v1/74db7374-5a34-49ec-8351-8458aafc57eg~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-07-10 21:26:40",
              value:
                " 天津机场进入测试标招标阶段，民航标准第一版提交，乌鲁木齐民航进展顺利，市场推广延后至8月，3. 民航合资启动、KA战略需要调整，4. 成都、佛山签署意向协议，5. Q2参加了全球物流技术、整车物流、制造业物流、汽车零部件物流等重要行业大会，累计获得2487条客户名录，627条深度客户线索。累计声量第七名",
              jd_id: 12093,
              old_value:
                "1. Q2实现营收1600万（其中产品销售占比71%，U-Pilot 占比21%，机场业务占比7%，新业务占比1%），同比2020年Q1增长79%。全年累计营收2540万，同比2020 H1增长62%；2. 天津机场进入测试标招标阶段，民航标准第一版提交，乌鲁木齐民航进展顺利，市场推广延后至8月，3. 民航合资启动、KA战略需要调整，4. 成都、佛山签署意向协议，5. Q2参加了全球物流技术、整车物流、制造业物流、汽车零部件物流等重要行业大会，累计获得2487条客户名录，627条深度客户线索。累计声量第七名",
              prop_key: "status_info",
              username: "闫颂秋",
              avatar:
                "https://s1-imfile.feishucdn.com/static-resource/v1/74db7374-5a34-49ec-8351-8458aafc57eg~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-07-08 09:12:32",
              value:
                "1. Q2实现营收1600万（其中产品销售占比71%，U-Pilot 占比21%，机场业务占比7%，新业务占比1%），同比2020年Q1增长79%。全年累计营收2540万，同比2020 H1增长62%；2. 天津机场进入测试标招标阶段，民航标准第一版提交，乌鲁木齐民航进展顺利，市场推广延后至8月，3. 民航合资启动、KA战略需要调整，4. 成都、佛山签署意向协议，5. Q2参加了全球物流技术、整车物流、制造业物流、汽车零部件物流等重要行业大会，累计获得2487条客户名录，627条深度客户线索。累计声量第七名。",
              jd_id: 11755,
              old_value:
                "1. Q2实现营收1600万（其中产品销售占比71%，U-Pilot 占比21%，机场业务占比7%，新业务占比1%），同比增长79%。全年累计营收2540万，同比增长62%；2. 天津机场进入测试标招标阶段，民航标准第一版提交，乌鲁木齐民航进展顺利，市场推广延后至8月，3. 民航合资启动、KA战略需要调整，4. 成都、佛山签署意向协议，5. Q2参加了全球物流技术、整车物流、制造业物流、汽车零部件物流等重要行业大会，累计获得2487条客户名录，627条深度客户线索。累计声量第七名。",
              prop_key: "status_info",
              username: "邱巍",
              avatar:
                "https://s3-imfile.feishucdn.com/static-resource/v1/af0b1d86-6b0d-4f80-b1d8-3d2a26a4447g~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-07-08 09:11:37",
              value:
                "1. Q2实现营收1600万（其中产品销售占比71%，U-Pilot 占比21%，机场业务占比7%，新业务占比1%），同比增长79%。全年累计营收2540万，同比增长62%；2. 天津机场进入测试标招标阶段，民航标准第一版提交，乌鲁木齐民航进展顺利，市场推广延后至8月，3. 民航合资启动、KA战略需要调整，4. 成都、佛山签署意向协议，5. Q2参加了全球物流技术、整车物流、制造业物流、汽车零部件物流等重要行业大会，累计获得2487条客户名录，627条深度客户线索。累计声量第七名。",
              jd_id: 11754,
              old_value:
                "1. Q2实现营收1600万，同比增长79%（产品销售71%，U-Pilot 21%，机场业务7%，新业务1%）。全年累计营收2540万，同比增长62%；2. 天津机场进入测试标招标阶段，民航标准第一版提交，乌鲁木齐民航市场推广筹备启动，3. 民航合资启动、KA战略需要调整，4. 成都、佛山签署意向协议，5. 截至5月，Q2累计获得1601条客户名录，224条深度客户线索。4-5月累计声量第七名。",
              prop_key: "status_info",
              username: "邱巍",
              avatar:
                "https://s3-imfile.feishucdn.com/static-resource/v1/af0b1d86-6b0d-4f80-b1d8-3d2a26a4447g~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-07-08 09:04:37",
              value:
                "1. Q2实现营收1600万，同比增长79%（产品销售71%，U-Pilot 21%，机场业务7%，新业务1%）。全年累计营收2540万，同比增长62%；2. 天津机场进入测试标招标阶段，民航标准第一版提交，乌鲁木齐民航市场推广筹备启动，3. 民航合资启动、KA战略需要调整，4. 成都、佛山签署意向协议，5. 截至5月，Q2累计获得1601条客户名录，224条深度客户线索。4-5月累计声量第七名。",
              jd_id: 11753,
              old_value:
                "1. 当季营收不及预期，目前Q2营收机会2400万。全年营收体量尚可支撑。需随行业上量需求及竞争态势调整策略。2. 天津机场进入测试标招标阶段，民航标准第一版提交，乌鲁木齐民航市场推广筹备启动，3. 民航合资启动、KA战略需要调整，4. 成都、佛山签署意向协议，5. 截至5月，Q2累计获得1601条客户名录，224条深度客户线索。4-5月累计声量第七名。",
              prop_key: "status_info",
              username: "邱巍",
              avatar:
                "https://s3-imfile.feishucdn.com/static-resource/v1/af0b1d86-6b0d-4f80-b1d8-3d2a26a4447g~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-06-02 08:44:34",
              value:
                "1. 当季营收不及预期，目前Q2营收机会2400万。全年营收体量尚可支撑。需随行业上量需求及竞争态势调整策略。2. 天津机场进入测试标招标阶段，民航标准第一版提交，乌鲁木齐民航市场推广筹备启动，3. 民航合资启动、KA战略需要调整，4. 成都、佛山签署意向协议，5. 截至5月，Q2累计获得1601条客户名录，224条深度客户线索。4-5月累计声量第七名。",
              jd_id: 9776,
              old_value:
                "1. 当季营收不及预期，目前Q2营收机会2400万。全年营收体量尚可支撑。需随行业上量需求及竞争态势调整策略。2. 天津机场进入测试标招标阶段，民航标准第一版提交，乌鲁木齐民航市场推广筹备启动，3. 民航合资启动、KA战略需要调整，4. 成都、佛山签署意向协议，5. 品牌声量排名第7",
              prop_key: "status_info",
              username: "邱巍",
              avatar:
                "https://s3-imfile.feishucdn.com/static-resource/v1/af0b1d86-6b0d-4f80-b1d8-3d2a26a4447g~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-06-02 08:43:20",
              value:
                "1. 当季营收不及预期，目前Q2营收机会2400万。全年营收体量尚可支撑。需随行业上量需求及竞争态势调整策略。2. 天津机场进入测试标招标阶段，民航标准第一版提交，乌鲁木齐民航市场推广筹备启动，3. 民航合资启动、KA战略需要调整，4. 成都、佛山签署意向协议，5. 品牌声量排名第7",
              jd_id: 9772,
              old_value:
                "1. Q2累计营收1.5M，营收机会41.9 M，加权后28.5M; 2. HKIA 已APC交付2台，OOG PO已下；乌鲁木齐首单签约；标准正常推进中；3. KA战略稳步推进，4. 成都政企合作达成共识；5. 4月全球物流大会等活动收获1200条客户线索，累计声量在初创企业中排名第六。",
              prop_key: "status_info",
              username: "邱巍",
              avatar:
                "https://s3-imfile.feishucdn.com/static-resource/v1/af0b1d86-6b0d-4f80-b1d8-3d2a26a4447g~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-06-01 14:22:42",
              value:
                "1. Q2累计营收1.5M，营收机会41.9 M，加权后28.5M; 2. HKIA 已APC交付2台，OOG PO已下；乌鲁木齐首单签约；标准正常推进中；3. KA战略稳步推进，4. 成都政企合作达成共识；5. 4月全球物流大会等活动收获1200条客户线索，累计声量在初创企业中排名第六。",
              jd_id: 9725,
              old_value:
                "1. Q2累计营收1.5M，营收机会41.9 M，加权后28.5M; 2. HKIA APC交付一台，OOG方案确定；乌鲁木齐首单签约；标准正常推进中；3. KA战略稳步推进，4. 成都政企合作达成共识；5. 4月全球物流大会等活动收获1200条客户线索，累计声量在初创企业中排名第六。",
              prop_key: "status_info",
              username: "彭进展",
              avatar:
                "https://s1-imfile.feishucdn.com/static-resource/v1/884a297b-63fa-4b01-b21b-6b9736fde99g~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-05-07 16:07:59",
              value:
                "1. Q2累计营收1.5M，营收机会41.9 M，加权后28.5M; 2. HKIA APC交付一台，OOG方案确定；乌鲁木齐首单签约；标准正常推进中；3. KA战略稳步推进，4. 成都政企合作达成共识；5. 4月全球物流大会等活动收获1200条客户线索，累计声量在初创企业中排名第六。",
              jd_id: 8697,
              old_value:
                "1. Q2累计营收15M，营收机会41.9 M，加权后28.5M; 2. HKIA APC交付一台，OOG方案确定；乌鲁木齐首单签约；标准正常推进中；3. KA战略稳步推进，4. 成都政企合作达成共识；5. 4月全球物流大会等活动收获1200条客户线索，累计声量在初创企业中排名第六。",
              prop_key: "status_info",
              username: "邱巍",
              avatar:
                "https://s3-imfile.feishucdn.com/static-resource/v1/af0b1d86-6b0d-4f80-b1d8-3d2a26a4447g~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-05-07 14:12:42",
              value:
                "1. Q2累计营收15M，营收机会41.9 M，加权后28.5M; 2. HKIA APC交付一台，OOG方案确定；乌鲁木齐首单签约；标准正常推进中；3. KA战略稳步推进，4. 成都政企合作达成共识；5. 4月全球物流大会等活动收获1200条客户线索，累计声量在初创企业中排名第六。",
              jd_id: 8682,
              old_value: "HKIA（APC交付一台，OOG方案确定）",
              prop_key: "status_info",
              username: "邱巍",
              avatar:
                "https://s3-imfile.feishucdn.com/static-resource/v1/af0b1d86-6b0d-4f80-b1d8-3d2a26a4447g~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-05-06 13:12:37",
              value: "HKIA（APC交付一台，OOG方案确定）",
              jd_id: 8436,
              old_value: "",
              prop_key: "status_info",
              username: "彭进展",
              avatar:
                "https://s1-imfile.feishucdn.com/static-resource/v1/884a297b-63fa-4b01-b21b-6b9736fde99g~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
          ],
        },
        {
          id: 1207,
          okr_id: 559,
          type: 0,
          relation_milestone_id: 0,
          name: "O1-KA2-物流产品和供应链：兼顾生产效率和质量管理并行，提升T05 1.0/T30 2.1一致可靠性，加速推进T05 2.0/T30 2.2研发进程，充分保障Q2营收计划和全年供应链安全。",
          result:
            "1. 解决全年千台级域控制器芯片的供应链安全问题。\n2. 部署运维阶段生产效率对比Q1 工时 减少  20 %；T05 1.0/T30 2.1提升一致性，嘉善生产效率提升一倍；\n3. T05 2.0和T30 2.2产品开发完成时间比原计划更快，就营销计划，成本和价格达成共识。",
          status: "smoothly",
          status_info:
            "供应链和生产工作顺利进行，T05 1.0/T30 2.1的4月生产任务按时完成，质量问题在增加，跟产组开始监督JXX进行工艺和质量一致性整改。T30 2.2首台车开始车电气调试和无人驾驶系统适配，T05 2.0研发进程基本按照节点走，略有延误；部署工时比Q1减少12.5%",
          progress: 60,
          score: 0,
          score_info:
            "供应链和生产工作顺利进行，T05 1.0/T30 2.1的一致性工作需要继续提升，4月顺着产量上升，质量问题在增加，跟产组的压力很大；嘉善T30的生产工时降低50%。T05 2.0/T30 2.2研发进程基本按照节点走，略有延误\n电子料、传感器风险基本解决，车辆交付根据项目进度控制节奏。",
          comments: "",
          start_time: "2021-03-01 00:00:00",
          end_time: "2021-06-30 00:00:00",
          weight: 30,
          author_id: 607,
          is_delete: 0,
          OwnerId: 10002,
          Username: "周鑫",
          owners: [
            {
              id: 10002,
              name: "周鑫",
            },
            {
              id: 10088,
              name: "魏冉",
            },
            {
              id: 10105,
              name: "邱巍",
            },
          ],
          tasks: null,
          stutusInfoHistories: [
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-06-01 17:00:01",
              value:
                "供应链和生产工作顺利进行，T05 1.0/T30 2.1的4月生产任务按时完成，质量问题在增加，跟产组开始监督JXX进行工艺和质量一致性整改。T30 2.2首台车开始车电气调试和无人驾驶系统适配，T05 2.0研发进程基本按照节点走，略有延误；部署工时比Q1减少12.5%",
              jd_id: 9746,
              old_value:
                "供应链和生产工作顺利进行，T05 1.0/T30 2.1的4月5月生产任务按时完成，质量问题在增加，跟产组开始监督JXX进行工艺和质量一致性整改。T30 2.2首台车开始车电气调试和无人驾驶系统适配，T05 2.0研发进程基本按照节点走，略有延误；部署工时比Q1减少12.5%",
              prop_key: "status_info",
              username: "周鑫",
              avatar:
                "https://s3-imfile.feishucdn.com/static-resource/v1/0e7995c5-1e22-41ee-b558-c15360ef3ebg~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-06-01 09:33:53",
              value:
                "供应链和生产工作顺利进行，T05 1.0/T30 2.1的4月5月生产任务按时完成，质量问题在增加，跟产组开始监督JXX进行工艺和质量一致性整改。T30 2.2首台车开始车电气调试和无人驾驶系统适配，T05 2.0研发进程基本按照节点走，略有延误；部署工时比Q1减少12.5%",
              jd_id: 9456,
              old_value:
                "供应链和生产工作顺利进行，T05 1.0/T30 2.1的4月5月生产任务按时完成，质量问题在增加，跟产组开始监督JXX进行工艺和质量一致性整改。T30 2.2首台车开始车电气调试和无人驾驶系统适配，T05 2.0研发进程基本按照节点走，略有延误",
              prop_key: "status_info",
              username: "周鑫",
              avatar:
                "https://s3-imfile.feishucdn.com/static-resource/v1/0e7995c5-1e22-41ee-b558-c15360ef3ebg~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-06-01 09:13:47",
              value:
                "供应链和生产工作顺利进行，T05 1.0/T30 2.1的4月5月生产任务按时完成，质量问题在增加，跟产组开始监督JXX进行工艺和质量一致性整改。T30 2.2首台车开始车电气调试和无人驾驶系统适配，T05 2.0研发进程基本按照节点走，略有延误",
              jd_id: 9453,
              old_value:
                "供应链和生产工作顺利进行，T05 1.0/T30 2.1的一致性工作需要继续提升，4月顺着产量上升，质量问题在增加，跟产组的压力很大。T05 2.0/T30 2.2研发进程基本按照节点走，略有延误",
              prop_key: "status_info",
              username: "周鑫",
              avatar:
                "https://s3-imfile.feishucdn.com/static-resource/v1/0e7995c5-1e22-41ee-b558-c15360ef3ebg~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-05-07 14:21:16",
              value:
                "供应链和生产工作顺利进行，T05 1.0/T30 2.1的一致性工作需要继续提升，4月顺着产量上升，质量问题在增加，跟产组的压力很大。T05 2.0/T30 2.2研发进程基本按照节点走，略有延误",
              jd_id: 8684,
              old_value: "",
              prop_key: "status_info",
              username: "邱巍",
              avatar:
                "https://s3-imfile.feishucdn.com/static-resource/v1/af0b1d86-6b0d-4f80-b1d8-3d2a26a4447g~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
          ],
        },
        {
          id: 1370,
          okr_id: 559,
          type: 0,
          relation_milestone_id: 0,
          name: "O1-KA3-售前、交付、运维和售后：前后协同、内外并举、建立质量跟踪闭环和标准化全流程运维体系，以满足多项目、规模化的高效交付需求；组建售后服务团队同时建立重点客户的跟踪保障机制。",
          result:
            "建立运维中心及重点客户运维机制，以香港海天码头AET车队运营为模板，复制到巴斯夫项目。提升FAE/FTS服务意识及客户服务满意度。明确售后服务团队具体工作职责及流程，并在Q2 开始发挥作用。",
          status: "smoothly",
          status_info:
            "运维小组协助巴斯夫现场小组半手工监控业务数据和业务效率，质量体系对所有现场质量问题跟踪处理。售后维修团队组建完毕，在BASF和长安等项目中发挥作用。",
          progress: 60,
          score: 0,
          score_info:
            "香港运维模式复制到巴斯夫工作已经开始，目前处于准备阶段。售后维修的早期团队已经组建。",
          comments: "",
          start_time: "2021-04-01 00:00:00",
          end_time: "2021-06-30 00:00:00",
          weight: 30,
          author_id: 18,
          is_delete: 0,
          OwnerId: 10304,
          Username: "于泰北",
          owners: [
            {
              id: 10304,
              name: "于泰北",
            },
            {
              id: 10028,
              name: "徐澍",
            },
            {
              id: 10094,
              name: "任志杰",
            },
            {
              id: 10088,
              name: "魏冉",
            },
            {
              id: 10002,
              name: "周鑫",
            },
          ],
          tasks: null,
          stutusInfoHistories: [
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-07-01 16:31:40",
              value:
                "运维小组协助巴斯夫现场小组半手工监控业务数据和业务效率，质量体系对所有现场质量问题跟踪处理。售后维修团队组建完毕，在BASF和长安等项目中发挥作用。",
              jd_id: 10713,
              old_value:
                "运维中心建立完成投入工作，紧盯所有客户运维；质量体系对所有现场质量问题跟踪处理；香港运维模式复制到巴斯夫工作已经开始，目前处于准备阶段。售后维修团队组建完毕，在BASF和长安等项目中发挥作用。",
              prop_key: "status_info",
              username: "周鑫",
              avatar:
                "https://s3-imfile.feishucdn.com/static-resource/v1/0e7995c5-1e22-41ee-b558-c15360ef3ebg~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-06-01 16:59:23",
              value:
                "运维中心建立完成投入工作，紧盯所有客户运维；质量体系对所有现场质量问题跟踪处理；香港运维模式复制到巴斯夫工作已经开始，目前处于准备阶段。售后维修团队组建完毕，在BASF和长安等项目中发挥作用。",
              jd_id: 9745,
              old_value:
                "运维中心建立完成投入工作，紧盯所有客户运维；香港运维模式复制到巴斯夫工作已经开始，目前处于准备阶段。售后维修团队组建完毕，在BASF和长安等项目中发挥作用。",
              prop_key: "status_info",
              username: "周鑫",
              avatar:
                "https://s3-imfile.feishucdn.com/static-resource/v1/0e7995c5-1e22-41ee-b558-c15360ef3ebg~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-06-01 09:37:27",
              value:
                "运维中心建立完成投入工作，紧盯所有客户运维；香港运维模式复制到巴斯夫工作已经开始，目前处于准备阶段。售后维修团队组建完毕，在BASF和长安等项目中发挥作用。",
              jd_id: 9458,
              old_value:
                "香港运维模式复制到巴斯夫工作已经开始，目前处于准备阶段。售后维修的早期团队已经组建。",
              prop_key: "status_info",
              username: "周鑫",
              avatar:
                "https://s3-imfile.feishucdn.com/static-resource/v1/0e7995c5-1e22-41ee-b558-c15360ef3ebg~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-05-07 14:21:30",
              value:
                "香港运维模式复制到巴斯夫工作已经开始，目前处于准备阶段。售后维修的早期团队已经组建。",
              jd_id: 8686,
              old_value: "",
              prop_key: "status_info",
              username: "邱巍",
              avatar:
                "https://s3-imfile.feishucdn.com/static-resource/v1/af0b1d86-6b0d-4f80-b1d8-3d2a26a4447g~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
          ],
        },
      ],
      children: [
        {
          id: 682,
          time_cycle_id: 5,
          name: "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
          department: "基础平台研发",
          status: "unconsidered",
          status_info: "",
          progress: 0,
          score: 0,
          score_info: "",
          comments: "",
          parent_id: 559,
          author_id: 26,
          o_type: 1,
          is_publish: 1,
          is_delete: 0,
          is_hidden: 0,
          start_time: "2021-04-01 00:00:00",
          end_time: "2021-06-30 00:00:00",
          OwnerId: 10006,
          weightSum: 0,
          Username: "张丹",
          owners: [
            {
              id: 10006,
              name: "张丹",
            },
            {
              id: 10007,
              name: "周小成",
            },
          ],
          visitors: null,
          keyResults: null,
          parent: null,
          stutusInfoHistories: null,
        },
        {
          id: 671,
          time_cycle_id: 5,
          name: "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
          department: "商业生态",
          status: "smoothly",
          status_info: "",
          progress: 0,
          score: 0,
          score_info: "",
          comments: "",
          parent_id: 559,
          author_id: 486,
          o_type: 1,
          is_publish: 1,
          is_delete: 0,
          is_hidden: 0,
          start_time: "2021-04-01 00:00:00",
          end_time: "2021-06-30 00:00:00",
          OwnerId: 10173,
          weightSum: 0,
          Username: "赖若果",
          owners: [
            {
              id: 10173,
              name: "赖若果",
            },
            {
              id: 10105,
              name: "邱巍",
            },
          ],
          visitors: null,
          keyResults: null,
          children: [
            {
              id: 7681,
              time_cycle_id: 5,
              name: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaA",
              department: "基础平台研发",
              status: "unconsidered",
              status_info: "",
              progress: 0,
              score: 0,
              score_info: "",
              comments: "",
              parent_id: 562,
              author_id: 26,
              o_type: 1,
              is_publish: 1,
              is_delete: 0,
              is_hidden: 0,
              start_time: "2021-04-01 00:00:00",
              end_time: "2021-06-30 00:00:00",
              OwnerId: 10006,
              weightSum: 0,
              Username: "张丹",
              owners: [
                {
                  id: 10006,
                  name: "张丹",
                },
                {
                  id: 10007,
                  name: "周小成",
                },
              ],
              visitors: null,
              keyResults: null,
              children: null,
              parent: null,
              stutusInfoHistories: null,
            },
            {
              id: 7683,
              time_cycle_id: 5,
              name: "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
              department: "基础平台研发",
              status: "unconsidered",
              status_info: "",
              progress: 0,
              score: 0,
              score_info: "",
              comments: "",
              parent_id: 562,
              author_id: 26,
              o_type: 1,
              is_publish: 1,
              is_delete: 0,
              is_hidden: 0,
              start_time: "2021-04-01 00:00:00",
              end_time: "2021-06-30 00:00:00",
              OwnerId: 10006,
              weightSum: 0,
              Username: "张丹",
              owners: [
                {
                  id: 10006,
                  name: "张丹",
                },
                {
                  id: 10007,
                  name: "周小成",
                },
              ],
              visitors: null,
              keyResults: null,
              children: null,
              parent: null,
              stutusInfoHistories: null,
            },
            {
              id: 7684,
              time_cycle_id: 5,
              name: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaA",
              department: "基础平台研发",
              status: "unconsidered",
              status_info: "",
              progress: 0,
              score: 0,
              score_info: "",
              comments: "",
              parent_id: 562,
              author_id: 26,
              o_type: 1,
              is_publish: 1,
              is_delete: 0,
              is_hidden: 0,
              start_time: "2021-04-01 00:00:00",
              end_time: "2021-06-30 00:00:00",
              OwnerId: 10030,
              weightSum: 0,
              Username: "蔡尧",
              owners: [
                {
                  id: 10030,
                  name: "蔡尧",
                },
              ],
              visitors: null,
              keyResults: null,
              children: null,
              parent: null,
              stutusInfoHistories: null,
            },
            {
              id: 775,
              time_cycle_id: 5,
              name: "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
              department: "规划控制",
              status: "unconsidered",
              status_info: "",
              progress: 0,
              score: 0,
              score_info: "",
              comments: "",
              parent_id: 682,
              author_id: 26,
              o_type: 1,
              is_publish: 1,
              is_delete: 0,
              is_hidden: 0,
              start_time: "2021-04-01 00:00:00",
              end_time: "2021-06-30 00:00:00",
              OwnerId: 10007,
              weightSum: 0,
              Username: "周小成",
              owners: [
                {
                  id: 10007,
                  name: "周小成",
                },
              ],
              visitors: null,
              keyResults: null,
              children: null,
              parent: null,
              stutusInfoHistories: null,
            },
            {
              id: 779,
              time_cycle_id: 5,
              name: "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH",
              department: "定位感知",
              status: "unconsidered",
              status_info: "",
              progress: 0,
              score: 0,
              score_info: "",
              comments: "",
              parent_id: 682,
              author_id: 24,
              o_type: 1,
              is_publish: 1,
              is_delete: 0,
              is_hidden: 0,
              start_time: "2021-04-01 00:00:00",
              end_time: "2021-06-30 00:00:00",
              OwnerId: 10006,
              weightSum: 0,
              Username: "张丹",
              owners: [
                {
                  id: 10006,
                  name: "张丹",
                },
              ],
              visitors: null,
              keyResults: null,
              children: null,
              parent: null,
              stutusInfoHistories: null,
            },
          ],
          parent: null,
          stutusInfoHistories: null,
        },
      ],
      parent: null,
      stutusInfoHistories: null,
    },
    {
      id: 560,
      time_cycle_id: 5,
      name: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
      department: "驭势科技",
      status: "unconsidered",
      status_info: "",
      progress: 89,
      score: 0,
      score_info: "",
      comments: "",
      parent_id: 0,
      author_id: 607,
      o_type: 2,
      is_publish: 1,
      is_delete: 0,
      is_hidden: 0,
      start_time: "2021-01-01 00:00:00",
      end_time: "2021-12-31 00:00:00",
      OwnerId: 10001,
      weightSum: 100,
      Username: "吴甘沙",
      owners: [
        {
          id: 10001,
          name: "吴甘沙",
        },
      ],
      visitors: null,
      keyResults: [
        {
          id: 1212,
          okr_id: 560,
          type: 0,
          relation_milestone_id: 0,
          name: "前后方（销售-交付-生产/供应链-研发）和左右手（方案组-职能部门）协同效率的提升（角色清晰、高效同步、及时应变）",
          result:
            "提升各业务关联部门有效沟通，有效信息更透明，减少前后方部门信息不对称性；方案组和职能部门之间的合作更高效顺畅，双方高效协同，合作效率更高。",
          status: "smoothly",
          status_info:
            "方案组+交付运维部门 和 商务销售部门 的协作流程运转顺利。每周开工厂物流销售交付同步例会，保持信息同步。香港机场和国内机场每周通过方案组pmo同步。",
          progress: 80,
          score: 0,
          score_info:
            "本月，方案组+交付运维部门 和 商务销售部门 的信息透明和流通有很大提升，虽然经过几次碰撞，磨合出了写作流程，下一步，需要提升机场销售组的协作。",
          comments: "",
          start_time: "2021-04-01 00:00:00",
          end_time: "2021-06-30 00:00:00",
          weight: 40,
          author_id: 18,
          is_delete: 0,
          OwnerId: 10002,
          Username: "周鑫",
          owners: [
            {
              id: 10002,
              name: "周鑫",
            },
            {
              id: 10003,
              name: "彭进展",
            },
            {
              id: 10004,
              name: "姜岩",
            },
            {
              id: 10105,
              name: "邱巍",
            },
            {
              id: 10043,
              name: "高丽萍",
            },
            {
              id: 10333,
              name: "祝明",
            },
          ],
          tasks: null,
          stutusInfoHistories: [
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-06-01 16:57:45",
              value:
                "方案组+交付运维部门 和 商务销售部门 的协作流程运转顺利。每周开工厂物流销售交付同步例会，保持信息同步。香港机场和国内机场每周通过方案组pmo同步。",
              jd_id: 9744,
              old_value:
                "方案组+交付运维部门 和 商务销售部门 的协作流程运转顺利。",
              prop_key: "status_info",
              username: "周鑫",
              avatar:
                "https://s3-imfile.feishucdn.com/static-resource/v1/0e7995c5-1e22-41ee-b558-c15360ef3ebg~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-06-01 09:40:35",
              value: "方案组+交付运维部门 和 商务销售部门 的协作流程运转顺利。",
              jd_id: 9463,
              old_value:
                "本月，方案组+交付运维部门 和 商务销售部门 的信息透明和流通有很大提升，虽然经过几次碰撞，磨合出了协作流程，下一步，需要提升机场销售组的协作。",
              prop_key: "status_info",
              username: "周鑫",
              avatar:
                "https://s3-imfile.feishucdn.com/static-resource/v1/0e7995c5-1e22-41ee-b558-c15360ef3ebg~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-05-07 15:42:11",
              value:
                "本月，方案组+交付运维部门 和 商务销售部门 的信息透明和流通有很大提升，虽然经过几次碰撞，磨合出了协作流程，下一步，需要提升机场销售组的协作。",
              jd_id: 8692,
              old_value:
                "本月，方案组+交付运维部门 和 商务销售部门 的信息透明和流通有很大提升，虽然经过几次碰撞，磨合出了写作流程，下一步，需要提升机场销售组的协作。",
              prop_key: "status_info",
              username: "邱巍",
              avatar:
                "https://s3-imfile.feishucdn.com/static-resource/v1/af0b1d86-6b0d-4f80-b1d8-3d2a26a4447g~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-05-07 14:23:07",
              value:
                "本月，方案组+交付运维部门 和 商务销售部门 的信息透明和流通有很大提升，虽然经过几次碰撞，磨合出了写作流程，下一步，需要提升机场销售组的协作。",
              jd_id: 8688,
              old_value: "",
              prop_key: "status_info",
              username: "邱巍",
              avatar:
                "https://s3-imfile.feishucdn.com/static-resource/v1/af0b1d86-6b0d-4f80-b1d8-3d2a26a4447g~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
          ],
        },
        {
          id: 1218,
          okr_id: 560,
          type: 0,
          relation_milestone_id: 0,
          name: "通过一系列新的激励机制让员工获得正效益",
          result:
            "完成年度非同凡响奖评选、年度人员晋升、新的激励机制正式颁布，让员工的付出带来相应的回报。同时展开内部调研，及时了解员工正负反馈。",
          status: "smoothly",
          status_info:
            "4月晋升顺利结束，2020年都非同凡响奖评选出台。晋升调研和复盘已经完成，正向激励反馈明显。云上NEO顺利结束",
          progress: 100,
          score: 0,
          score_info:
            "4月晋升顺利结束，2020年都非同凡响奖评选出台。晋升调研和复盘已经完成，正向激励反馈明显。云上NEO顺利结束",
          comments: "",
          start_time: "2021-04-01 00:00:00",
          end_time: "2022-06-30 00:00:00",
          weight: 30,
          author_id: 605,
          is_delete: 0,
          OwnerId: 10394,
          Username: "张燕",
          owners: [
            {
              id: 10394,
              name: "张燕",
            },
          ],
          tasks: null,
          stutusInfoHistories: [
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-06-01 11:35:01",
              value:
                "4月晋升顺利结束，2020年都非同凡响奖评选出台。晋升调研和复盘已经完成，正向激励反馈明显。云上NEO顺利结束",
              jd_id: 9657,
              old_value:
                "4月晋升顺利结束，2020年都非同凡响奖打分出台，待甘沙最后决策。云上NEO顺利结束",
              prop_key: "status_info",
              username: "张燕",
              avatar:
                "https://s1-fs.pstatp.com/static-resource/v1/ef361563-435b-476f-811f-29a6a6726d8g~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-05-06 15:17:52",
              value:
                "4月晋升顺利结束，2020年都非同凡响奖打分出台，待甘沙最后决策。云上NEO顺利结束",
              jd_id: 8472,
              old_value: "",
              prop_key: "status_info",
              username: "张燕",
              avatar:
                "https://s1-fs.pstatp.com/static-resource/v1/ef361563-435b-476f-811f-29a6a6726d8g~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
          ],
        },
        {
          id: 1220,
          okr_id: 560,
          type: 0,
          relation_milestone_id: 0,
          name: "以OKR和PI系统为基础抓手，建立平等透明、高效协同的组织基础设施并逐步完成高效整合应用。",
          result:
            "实现OKR/周报/工时的填报并实现飞书的高效打通整合，填报便利性及效率有明显提升并可以在员工中形成口碑推荐，节省员工  %的时间。\n达到90%员工以上完成设定个人OKR，并定期与主管进行个人OKR讨论和活跃更新。",
          status: "smoothly",
          status_info:
            "【6/30】目前有156人建立了个人OKR（其中正式员工143人）。目前有150人使用飞书小程序。",
          progress: 90,
          score: 0,
          score_info:
            "【5/5】OKR和周报工时工具已经上线。后面着重推广和优化。\n【5/31】据统计数据：目前有121人创建了个人OKR；110人使用周报小程序。\n【6/13】据统计数据：目前有125人建立了个人OKR；（其中正式员工110人）\n【6/30】据统计数据：目前有156人建立了个人OKR；（其中正式员工143人）",
          comments: "",
          start_time: "2021-04-01 00:00:00",
          end_time: "2021-06-30 00:00:00",
          weight: 30,
          author_id: 196,
          is_delete: 0,
          OwnerId: 10002,
          Username: "周鑫",
          owners: [
            {
              id: 10002,
              name: "周鑫",
            },
            {
              id: 10183,
              name: "雷刚",
            },
          ],
          tasks: null,
          stutusInfoHistories: [
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-07-01 11:45:00",
              value:
                "【6/30】目前有156人建立了个人OKR（其中正式员工143人）。目前有150人使用飞书小程序。",
              jd_id: 10637,
              old_value:
                "【6/30】目前有156人建立了个人OKR（其中正式员工143人）。【6/13】目前有125人建立个人OKR（其中正式员工110人）【6/4】点评功能上线。【5/31】据统计数据：目前有121人创建了个人OKR；110人使用周报小程序。【5/5】OKR和周报工时工具已经上线。后面着重推广和优化",
              prop_key: "status_info",
              username: "雷刚",
              avatar:
                "https://s1-imfile.feishucdn.com/static-resource/v1/f2163ddb-3ef5-425b-ae0f-f8ec8f4d7d8g~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-07-01 11:39:56",
              value:
                "【6/30】目前有156人建立了个人OKR（其中正式员工143人）。【6/13】目前有125人建立个人OKR（其中正式员工110人）【6/4】点评功能上线。【5/31】据统计数据：目前有121人创建了个人OKR；110人使用周报小程序。【5/5】OKR和周报工时工具已经上线。后面着重推广和优化",
              jd_id: 10635,
              old_value:
                "【6/30】目前有156人建立了个人OKR。【6/13】目前有125人建立个人OKR（其中正式员工110人）【6/4】点评功能上线。【5/31】据统计数据：目前有121人创建了个人OKR；110人使用周报小程序。【5/5】OKR和周报工时工具已经上线。后面着重推广和优化",
              prop_key: "status_info",
              username: "雷刚",
              avatar:
                "https://s1-imfile.feishucdn.com/static-resource/v1/f2163ddb-3ef5-425b-ae0f-f8ec8f4d7d8g~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-07-01 11:37:08",
              value:
                "【6/30】目前有156人建立了个人OKR。【6/13】目前有125人建立个人OKR（其中正式员工110人）【6/4】点评功能上线。【5/31】据统计数据：目前有121人创建了个人OKR；110人使用周报小程序。【5/5】OKR和周报工时工具已经上线。后面着重推广和优化",
              jd_id: 10629,
              old_value:
                "【6/13】目前有125人建立个人OKR（其中正式员工110人）【6/4】点评功能上线。【5/31】据统计数据：目前有121人创建了个人OKR；110人使用周报小程序。【5/5】OKR和周报工时工具已经上线。后面着重推广和优化",
              prop_key: "status_info",
              username: "雷刚",
              avatar:
                "https://s1-imfile.feishucdn.com/static-resource/v1/f2163ddb-3ef5-425b-ae0f-f8ec8f4d7d8g~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-06-13 21:55:14",
              value:
                "【6/13】目前有125人建立个人OKR（其中正式员工110人）【6/4】点评功能上线。【5/31】据统计数据：目前有121人创建了个人OKR；110人使用周报小程序。【5/5】OKR和周报工时工具已经上线。后面着重推广和优化",
              jd_id: 9941,
              old_value:
                "【6/4】点评功能上线。【5/31】据统计数据：目前有121人创建了个人OKR；110人使用周报小程序。【5/5】OKR和周报工时工具已经上线。后面着重推广和优化",
              prop_key: "status_info",
              username: "雷刚",
              avatar:
                "https://s1-imfile.feishucdn.com/static-resource/v1/f2163ddb-3ef5-425b-ae0f-f8ec8f4d7d8g~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-06-11 14:39:42",
              value:
                "【6/4】点评功能上线。【5/31】据统计数据：目前有121人创建了个人OKR；110人使用周报小程序。【5/5】OKR和周报工时工具已经上线。后面着重推广和优化",
              jd_id: 9915,
              old_value:
                "【5/31】据统计数据：目前有121人创建了个人OKR；110人使用周报小程序。【5/5】OKR和周报工时工具已经上线。后面着重推广和优化",
              prop_key: "status_info",
              username: "雷刚",
              avatar:
                "https://s1-imfile.feishucdn.com/static-resource/v1/f2163ddb-3ef5-425b-ae0f-f8ec8f4d7d8g~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-06-01 01:02:20",
              value:
                "【5/31】据统计数据：目前有121人创建了个人OKR；110人使用周报小程序。【5/5】OKR和周报工时工具已经上线。后面着重推广和优化",
              jd_id: 9450,
              old_value: "OKR和周报工时工具已经上线。后面着重推广和优化",
              prop_key: "status_info",
              username: "雷刚",
              avatar:
                "https://s1-imfile.feishucdn.com/static-resource/v1/f2163ddb-3ef5-425b-ae0f-f8ec8f4d7d8g~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-05-07 15:41:21",
              value: "OKR和周报工时工具已经上线。后面着重推广和优化",
              jd_id: 8690,
              old_value: "",
              prop_key: "status_info",
              username: "邱巍",
              avatar:
                "https://s3-imfile.feishucdn.com/static-resource/v1/af0b1d86-6b0d-4f80-b1d8-3d2a26a4447g~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
          ],
        },
      ],
      children: null,
      parent: null,
      stutusInfoHistories: null,
    },
    {
      id: 561,
      time_cycle_id: 5,
      name: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
      department: "驭势科技",
      status: "unconsidered",
      status_info: "",
      progress: 94,
      score: 0,
      score_info: "",
      comments: "",
      parent_id: 0,
      author_id: 607,
      o_type: 2,
      is_publish: 1,
      is_delete: 0,
      is_hidden: 0,
      start_time: "2021-01-01 00:00:00",
      end_time: "2021-12-31 00:00:00",
      OwnerId: 10049,
      weightSum: 100,
      Username: "江宗哲",
      owners: [
        {
          id: 10049,
          name: "江宗哲",
        },
      ],
      visitors: null,
      keyResults: [
        {
          id: 1371,
          okr_id: 561,
          type: 0,
          relation_milestone_id: 0,
          name: "设立天津持股平台，同时将持股平台移至税收优惠较高的地方",
          result: "司马驹认购份额转让，同时GP持股比例调整至最低。\n",
          status: "completed",
          status_info: "已完成員工持股平台。",
          progress: 100,
          score: 0,
          score_info: "",
          comments: "",
          start_time: "2021-04-01 00:00:00",
          end_time: "2021-06-30 00:00:00",
          weight: 30,
          author_id: 62,
          is_delete: 0,
          OwnerId: 10049,
          Username: "江宗哲",
          owners: [
            {
              id: 10049,
              name: "江宗哲",
            },
          ],
          tasks: null,
          stutusInfoHistories: [
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-05-05 16:47:19",
              value: "已完成員工持股平台。",
              jd_id: 8214,
              old_value: "",
              prop_key: "status_info",
              username: "江宗哲",
              avatar:
                "https://s1-imfile.feishucdn.com/static-resource/v1/33de3e12-62af-490a-ac17-4e1b29e50f5g~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
          ],
        },
        {
          id: 1372,
          okr_id: 561,
          type: 0,
          relation_milestone_id: 0,
          name: "聘请四大会计师事务所针对公司目前财务制度及体系进行健检，评估财务数据是否存在硬伤，包含(1)收入确认原则 (2)股权基础给付(3)或有负债的评估 (4)收入与知识产权的关联性(5)研发项目的立项归集和统计\n",
          result: "确认是否有硬伤，若有，同时进行整改计划。确保没有IPO硬伤。",
          status: "completed",
          status_info:
            "安永會計師事務所開始審查，初步問題已辨識出來。仍需要進一步訪談溝通",
          progress: 90,
          score: 0,
          score_info: "",
          comments: "",
          start_time: "2021-04-01 00:00:00",
          end_time: "2021-06-30 00:00:00",
          weight: 30,
          author_id: 62,
          is_delete: 0,
          OwnerId: 10049,
          Username: "江宗哲",
          owners: [
            {
              id: 10049,
              name: "江宗哲",
            },
          ],
          tasks: null,
          stutusInfoHistories: [
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-06-24 17:04:59",
              value:
                "安永會計師事務所開始審查，初步問題已辨識出來。仍需要進一步訪談溝通",
              jd_id: 10148,
              old_value: "安永會計師事務所開始審查，預計6月底完成。",
              prop_key: "status_info",
              username: "江宗哲",
              avatar:
                "https://s1-imfile.feishucdn.com/static-resource/v1/33de3e12-62af-490a-ac17-4e1b29e50f5g~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-05-31 10:22:39",
              value: "安永會計師事務所開始審查，預計6月底完成。",
              jd_id: 9194,
              old_value: "已確定由安永會計師事務所於5月底進場。",
              prop_key: "status_info",
              username: "江宗哲",
              avatar:
                "https://s1-imfile.feishucdn.com/static-resource/v1/33de3e12-62af-490a-ac17-4e1b29e50f5g~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-05-05 16:49:35",
              value: "已確定由安永會計師事務所於5月底進場。",
              jd_id: 8224,
              old_value: "",
              prop_key: "status_info",
              username: "江宗哲",
              avatar:
                "https://s1-imfile.feishucdn.com/static-resource/v1/33de3e12-62af-490a-ac17-4e1b29e50f5g~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
          ],
        },
        {
          id: 1374,
          okr_id: 561,
          type: 0,
          relation_milestone_id: 0,
          name: "根据Q1執行LDD辨识出的问题，制定整改计划并落实",
          result: "清除LDD辨识出来的硬伤。",
          status: "completed",
          status_info:
            "根據新規定外部顧問不需要額外設定持股平台，協議控制已與上海交易所完成溝通。",
          progress: 100,
          score: 0,
          score_info: "",
          comments: "",
          start_time: "2021-04-01 00:00:00",
          end_time: "2021-06-30 00:00:00",
          weight: 30,
          author_id: 62,
          is_delete: 0,
          OwnerId: 0,
          Username: "",
          owners: null,
          tasks: null,
          stutusInfoHistories: [
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-06-24 17:03:56",
              value:
                "根據新規定外部顧問不需要額外設定持股平台，協議控制已與上海交易所完成溝通。",
              jd_id: 10144,
              old_value:
                "外部顧問持股平台設立尚未完成，協議控制已與上海交易所完成溝通。",
              prop_key: "status_info",
              username: "江宗哲",
              avatar:
                "https://s1-imfile.feishucdn.com/static-resource/v1/33de3e12-62af-490a-ac17-4e1b29e50f5g~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-05-31 10:22:13",
              value:
                "外部顧問持股平台設立尚未完成，協議控制已與上海交易所完成溝通。",
              jd_id: 9193,
              old_value: "尚餘協議控制及外部顧問持股平台設立尚未完成。",
              prop_key: "status_info",
              username: "江宗哲",
              avatar:
                "https://s1-imfile.feishucdn.com/static-resource/v1/33de3e12-62af-490a-ac17-4e1b29e50f5g~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-05-05 16:49:07",
              value: "尚餘協議控制及外部顧問持股平台設立尚未完成。",
              jd_id: 8221,
              old_value: "",
              prop_key: "status_info",
              username: "江宗哲",
              avatar:
                "https://s1-imfile.feishucdn.com/static-resource/v1/33de3e12-62af-490a-ac17-4e1b29e50f5g~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
          ],
        },
        {
          id: 1373,
          okr_id: 561,
          type: 0,
          relation_milestone_id: 0,
          name: "确定投行券商",
          result: "随业务的推进情况，启动辅导。",
          status: "smoothly",
          status_info:
            "已接觸中金/中信證券/中信建投/華泰證券，最終三家選一家。",
          progress: 70,
          score: 0,
          score_info: "",
          comments: "",
          start_time: "2021-04-01 00:00:00",
          end_time: "2021-06-30 00:00:00",
          weight: 10,
          author_id: 62,
          is_delete: 0,
          OwnerId: 10049,
          Username: "江宗哲",
          owners: [
            {
              id: 10049,
              name: "江宗哲",
            },
          ],
          tasks: null,
          stutusInfoHistories: [
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-06-01 13:07:03",
              value: "已接觸中金/中信證券/中信建投/華泰證券，最終三家選一家。",
              jd_id: 9712,
              old_value: "已接觸中金/中信證券/中信建投/華泰證券。",
              prop_key: "status_info",
              username: "江宗哲",
              avatar:
                "https://s1-imfile.feishucdn.com/static-resource/v1/33de3e12-62af-490a-ac17-4e1b29e50f5g~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-05-05 16:48:02",
              value: "已接觸中金/中信證券/中信建投/華泰證券。",
              jd_id: 8217,
              old_value: "",
              prop_key: "status_info",
              username: "江宗哲",
              avatar:
                "https://s1-imfile.feishucdn.com/static-resource/v1/33de3e12-62af-490a-ac17-4e1b29e50f5g~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
          ],
        },
      ],
      children: null,
      parent: null,
      stutusInfoHistories: null,
    },
    {
      id: 562,
      time_cycle_id: 5,
      name: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaA",
      department: "驭势科技",
      status: "unconsidered",
      status_info: "",
      progress: 85,
      score: 0,
      score_info: "",
      comments: "",
      parent_id: 0,
      author_id: 607,
      o_type: 2,
      is_publish: 1,
      is_delete: 0,
      is_hidden: 0,
      start_time: "2021-01-01 00:00:00",
      end_time: "2021-12-31 00:00:00",
      OwnerId: 10001,
      weightSum: 100,
      Username: "吴甘沙",
      owners: [
        {
          id: 10001,
          name: "吴甘沙",
        },
      ],
      visitors: null,
      keyResults: [
        {
          id: 1224,
          okr_id: 562,
          type: 0,
          relation_milestone_id: 0,
          name: "完成主机厂需要的投名状初体验（L3+HZP+数据闭环）",
          result:
            "通过乘用车方案组整合投名状整体方案设计，各业务模块欠缺业务补差，使HZP可具量产性，同时建立公司数据闭环管理平台（设备统筹及统一的平台）。",
          status: "hard",
          status_info:
            "数据闭环：标注、训练部分已集成进洛书云端，同时开展与基础研发感知团队训练上云的工作。L3沪嘉演示道路已实现桃浦下匝道口，扩展外环匝道；DSSAD完成车端嵌入式实现和车云连接开发；完成主辅双线失效切换功能v1.0；一汽AEB项目已完成海南测试，达到cncap 5星水平；已提交中国智能网联汽车创新应用路线图。HZP4.0 POC正在做代码集成工作。整体工作进度不足，主要原因是和物流方案组资源冲突和研发人力不足；E115线控待一汽开放；东风LAPA车辆到位。",
          progress: 70,
          score: 0,
          score_info: "",
          comments: "",
          start_time: "2021-04-01 00:00:00",
          end_time: "2021-06-30 00:00:00",
          weight: 40,
          author_id: 46,
          is_delete: 0,
          OwnerId: 10043,
          Username: "高丽萍",
          owners: [
            {
              id: 10043,
              name: "高丽萍",
            },
            {
              id: 10023,
              name: "叶凌峡",
            },
          ],
          tasks: null,
          stutusInfoHistories: [
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-07-02 15:07:35",
              value:
                "数据闭环：标注、训练部分已集成进洛书云端，同时开展与基础研发感知团队训练上云的工作。L3沪嘉演示道路已实现桃浦下匝道口，扩展外环匝道；DSSAD完成车端嵌入式实现和车云连接开发；完成主辅双线失效切换功能v1.0；一汽AEB项目已完成海南测试，达到cncap 5星水平；已提交中国智能网联汽车创新应用路线图。HZP4.0 POC正在做代码集成工作。整体工作进度不足，主要原因是和物流方案组资源冲突和研发人力不足；E115线控待一汽开放；东风LAPA车辆到位。",
              jd_id: 10955,
              old_value:
                "数据闭环：标注、训练部分已集成进洛书云端，同时开展与基础研发感知团队训练上云的工作；继续开展提高Dolly检测标注和训练效率，缩短发布周期的工作。L3沪嘉演示道路扩展到桃浦；DSSAD完成与车云结合开发；完成主辅双线失效切换功能v1.0；一汽AEB项目正常进行；已提交中国智能网联汽车创新应用路线图。HZP4.0核心算法问题解决：单目DLO-VIO目前解决了直道初始化成功率低、跟踪lost、尺度缩小等问题，并将FPS从5提升到30；E115线控待一汽开放；东风LAPA车辆尚未到位。",
              prop_key: "status_info",
              username: "高丽萍",
              avatar:
                "https://s3-imfile.feishucdn.com/static-resource/v1/f379164f-f5d8-4741-8db4-ee0d3c29e8dg~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-05-31 17:02:09",
              value:
                "数据闭环：标注、训练部分已集成进洛书云端，同时开展与基础研发感知团队训练上云的工作；继续开展提高Dolly检测标注和训练效率，缩短发布周期的工作。L3沪嘉演示道路扩展到桃浦；DSSAD完成与车云结合开发；完成主辅双线失效切换功能v1.0；一汽AEB项目正常进行；已提交中国智能网联汽车创新应用路线图。HZP4.0核心算法问题解决：单目DLO-VIO目前解决了直道初始化成功率低、跟踪lost、尺度缩小等问题，并将FPS从5提升到30；E115线控待一汽开放；东风LAPA车辆尚未到位。",
              jd_id: 9404,
              old_value:
                "数据闭环进展顺利，与AI研究院的初版闭环已实现（以DollyMonitor和红绿灯为目标，配合部分车端手工操作）；HZP算法研发难度大，推进较缓慢；L3亮点挖掘中，一汽项目进展顺利。E115车辆到位，但等待一汽开放线控。",
              prop_key: "status_info",
              username: "高丽萍",
              avatar:
                "https://s3-imfile.feishucdn.com/static-resource/v1/f379164f-f5d8-4741-8db4-ee0d3c29e8dg~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-05-05 22:10:10",
              value:
                "数据闭环进展顺利，与AI研究院的初版闭环已实现（以DollyMonitor和红绿灯为目标，配合部分车端手工操作）；HZP算法研发难度大，推进较缓慢；L3亮点挖掘中，一汽项目进展顺利。E115车辆到位，但等待一汽开放线控。",
              jd_id: 8274,
              old_value: "",
              prop_key: "status_info",
              username: "高丽萍",
              avatar:
                "https://s3-imfile.feishucdn.com/static-resource/v1/f379164f-f5d8-4741-8db4-ee0d3c29e8dg~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
          ],
        },
        {
          id: 1222,
          okr_id: 562,
          type: 0,
          relation_milestone_id: 0,
          name: "全力推进UC2200 （850f)的交付，确保下半年控制器的供应，不因为供应链的短缺而掉链子。",
          result:
            "在Q3 底前完成UC2200的整体/软硬件交付，对比桂冠3的效能和可靠性指标有     提升。",
          status: "smoothly",
          status_info:
            "0630：UC2200 DV2已经在T30 2.2.1首车试装运行，UC2200 的DV3已准备样机给T03 2.0首车试装；",
          progress: 100,
          score: 0,
          score_info: "",
          comments: "",
          start_time: "2021-04-01 00:00:00",
          end_time: "2021-09-30 00:00:00",
          weight: 30,
          author_id: 19,
          is_delete: 0,
          OwnerId: 10004,
          Username: "姜岩",
          owners: [
            {
              id: 10004,
              name: "姜岩",
            },
          ],
          tasks: null,
          stutusInfoHistories: [
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-07-07 17:48:19",
              value:
                "0630：UC2200 DV2已经在T30 2.2.1首车试装运行，UC2200 的DV3已准备样机给T03 2.0首车试装；",
              jd_id: 11658,
              old_value:
                "0530：uc2200软硬件开发ontrack进行：UC2200 DV2已完成对T30 2.2.1的首台车装车测试，初步安装完成，UC2200 DV3 已回板20pcs,软硬件持续开发中，可满足原计划6月底最大10台的临时上车测试要求；桂冠从850P高配切换升级到850P低配版本，软硬件切换完成，羽默工厂正在开始200台的生产组装测试；",
              prop_key: "status_info",
              username: "姜岩",
              avatar:
                "https://s3-imfile.feishucdn.com/static-resource/v1/f1546616-8246-4e63-ae51-a9d1dd4242ag~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-06-01 14:14:01",
              value:
                "0530：uc2200软硬件开发ontrack进行：UC2200 DV2已完成对T30 2.2.1的首台车装车测试，初步安装完成，UC2200 DV3 已回板20pcs,软硬件持续开发中，可满足原计划6月底最大10台的临时上车测试要求；桂冠从850P高配切换升级到850P低配版本，软硬件切换完成，羽默工厂正在开始200台的生产组装测试；",
              jd_id: 9719,
              old_value: "850 mcu断货隐患消除；uc2200软硬件开发按计划进行",
              prop_key: "status_info",
              username: "姜岩",
              avatar:
                "https://s3-imfile.feishucdn.com/static-resource/v1/f1546616-8246-4e63-ae51-a9d1dd4242ag~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-05-06 13:42:59",
              value: "850 mcu断货隐患消除；uc2200软硬件开发按计划进行",
              jd_id: 8454,
              old_value: "",
              prop_key: "status_info",
              username: "姜岩",
              avatar:
                "https://s3-imfile.feishucdn.com/static-resource/v1/f1546616-8246-4e63-ae51-a9d1dd4242ag~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
          ],
        },
        {
          id: 1223,
          okr_id: 562,
          type: 0,
          relation_milestone_id: 0,
          name: "RoboTaxi及小U在开放道路的能力上的指标明显提升，更具竞争性。",
          result:
            "武汉Robotaxi 无接管数据达到       KM，累计里程达到    公里，交付   条路线，并为领航项目二期做好准备。深圳Robotaxi 拿牌照。小U安全无接管数据达到1000KM，指定区域避障通行能力再度提升（通行无接管500KM），并与2-3家KA形成落地行合作。",
          status: "smoothly",
          status_info:
            "小U 0530：小U安全性180km，通过性361km（新路线和新车引入）。安全性问题收敛到cutin以及误检闯红灯，cutin机制有较大更新在进一步验证，闯红灯试验远程运维的方式。中通项目于6月初入场，沙特车辆已进入到内场压力测试阶段，6月底入场。Robotaxi 0630：6月测试里程3.6w公里，总测试里程10w+公里，部署新增路线100公里，mpi 50+公里",
          progress: 90,
          score: 0,
          score_info: "",
          comments: "",
          start_time: "2021-04-01 00:00:00",
          end_time: "2021-06-30 00:00:00",
          weight: 30,
          author_id: 19,
          is_delete: 0,
          OwnerId: 10003,
          Username: "彭进展",
          owners: [
            {
              id: 10003,
              name: "彭进展",
            },
            {
              id: 10004,
              name: "姜岩",
            },
          ],
          tasks: null,
          stutusInfoHistories: [
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-07-07 17:46:19",
              value:
                "小U 0530：小U安全性180km，通过性361km（新路线和新车引入）。安全性问题收敛到cutin以及误检闯红灯，cutin机制有较大更新在进一步验证，闯红灯试验远程运维的方式。中通项目于6月初入场，沙特车辆已进入到内场压力测试阶段，6月底入场。Robotaxi 0630：6月测试里程3.6w公里，总测试里程10w+公里，部署新增路线100公里，mpi 50+公里",
              jd_id: 11647,
              old_value:
                "小U 0530：小U安全性180km，通过性361km（新路线和新车引入）。安全性问题收敛到cutin以及误检闯红灯，cutin机制有较大更新在进一步验证，闯红灯试验远程运维的方式。中通项目于6月初入场，沙特车辆已进入到内场压力测试阶段，6月底入场。Robotaxi 0630：6月测试里程3.6w公里，总测试里程10w+公里，部署新增路线100公里",
              prop_key: "status_info",
              username: "姜岩",
              avatar:
                "https://s3-imfile.feishucdn.com/static-resource/v1/f1546616-8246-4e63-ae51-a9d1dd4242ag~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-07-07 17:45:39",
              value:
                "小U 0530：小U安全性180km，通过性361km（新路线和新车引入）。安全性问题收敛到cutin以及误检闯红灯，cutin机制有较大更新在进一步验证，闯红灯试验远程运维的方式。中通项目于6月初入场，沙特车辆已进入到内场压力测试阶段，6月底入场。Robotaxi 0630：6月测试里程3.6w公里，总测试里程10w+公里，部署新增路线100公里",
              jd_id: 11645,
              old_value:
                "小U 0530：小U安全性180km，通过性361km（新路线和新车引入）。安全性问题收敛到cutin以及误检闯红灯，cutin机制有较大更新在进一步验证，闯红灯试验远程运维的方式。中通项目于6月初入场，沙特车辆已进入到内场压力测试阶段，6月底入场。Robotaxi 0530：乘客hmi发布前场；日志片段打包上传功能发布前场，开始按周统计接管原因和bug分类；验证线路扩展提速到10公里/2天；车端功能持续优化，单月测试里程1.5w公里；vv6.4和vv6.5到深圳开始开辟路线启动路测（暂不考牌照）",
              prop_key: "status_info",
              username: "姜岩",
              avatar:
                "https://s3-imfile.feishucdn.com/static-resource/v1/f1546616-8246-4e63-ae51-a9d1dd4242ag~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-06-02 10:36:21",
              value:
                "小U 0530：小U安全性180km，通过性361km（新路线和新车引入）。安全性问题收敛到cutin以及误检闯红灯，cutin机制有较大更新在进一步验证，闯红灯试验远程运维的方式。中通项目于6月初入场，沙特车辆已进入到内场压力测试阶段，6月底入场。Robotaxi 0530：乘客hmi发布前场；日志片段打包上传功能发布前场，开始按周统计接管原因和bug分类；验证线路扩展提速到10公里/2天；车端功能持续优化，单月测试里程1.5w公里；vv6.4和vv6.5到深圳开始开辟路线启动路测（暂不考牌照）",
              jd_id: 9781,
              old_value:
                "小U 0530：小U安全性180km，通过性361km。安全性问题收敛到cutin以及误检闯红灯，cutin机制近期有较大更新，需要进一步验证，闯灯正通过远程运维的方式解决。中通项目于6月初入场，沙特车辆已进入到内场压力测试阶段，6月底入场。；robotaxi 0530：乘客hmi发布前场；日志片段打包上传功能发布前场，开始按周统计接管原因和bug分类；验证线路扩展提速到10公里/2天；车端功能持续优化，单月测试里程1.5w公里；vv6.4和vv6.5到深圳开始开辟路线启动路测（暂不考牌照）",
              prop_key: "status_info",
              username: "彭进展",
              avatar:
                "https://s1-imfile.feishucdn.com/static-resource/v1/884a297b-63fa-4b01-b21b-6b9736fde99g~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-06-02 09:48:34",
              value:
                "小U 0530：小U安全性180km，通过性361km。安全性问题收敛到cutin以及误检闯红灯，cutin机制近期有较大更新，需要进一步验证，闯灯正通过远程运维的方式解决。中通项目于6月初入场，沙特车辆已进入到内场压力测试阶段，6月底入场。；robotaxi 0530：乘客hmi发布前场；日志片段打包上传功能发布前场，开始按周统计接管原因和bug分类；验证线路扩展提速到10公里/2天；车端功能持续优化，单月测试里程1.5w公里；vv6.4和vv6.5到深圳开始开辟路线启动路测（暂不考牌照）",
              jd_id: 9778,
              old_value:
                "小U安全MPI 500KM，通行 300KM；中通和沙特应用推进中；robotaxi 0530：乘客hmi发布前场；日志片段打包上传功能发布前场，开始按周统计接管原因和bug分类；验证线路扩展提速到10公里/2天；车端功能持续优化，单月测试里程1.5w公里；vv6.4和vv6.5到深圳开始开辟路线启动路测（暂不考牌照）",
              prop_key: "status_info",
              username: "周小成",
              avatar:
                "https://s1-imfile.feishucdn.com/static-resource/v1/16197a6c-d0fd-410b-8917-b403a98fa16g~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-06-01 14:18:32",
              value:
                "小U安全MPI 500KM，通行 300KM；中通和沙特应用推进中；robotaxi 0530：乘客hmi发布前场；日志片段打包上传功能发布前场，开始按周统计接管原因和bug分类；验证线路扩展提速到10公里/2天；车端功能持续优化，单月测试里程1.5w公里；vv6.4和vv6.5到深圳开始开辟路线启动路测（暂不考牌照）",
              jd_id: 9724,
              old_value:
                "小U安全MPI 500KM，通行 300KM；中通和沙特应用推进中；robotaxi 0530：乘客hmi发布前场；日志片段打包上传功能发布前场；按周统计接管原因和bug分类；线路扩展验证提速到10公里/2天；车端功能持续优化；vv6.4和vv6.5到深圳开始开辟路线启动路测（暂不考牌照）",
              prop_key: "status_info",
              username: "姜岩",
              avatar:
                "https://s3-imfile.feishucdn.com/static-resource/v1/f1546616-8246-4e63-ae51-a9d1dd4242ag~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-06-01 14:17:15",
              value:
                "小U安全MPI 500KM，通行 300KM；中通和沙特应用推进中；robotaxi 0530：乘客hmi发布前场；日志片段打包上传功能发布前场；按周统计接管原因和bug分类；线路扩展验证提速到10公里/2天；车端功能持续优化；vv6.4和vv6.5到深圳开始开辟路线启动路测（暂不考牌照）",
              jd_id: 9723,
              old_value:
                "小U安全MPI 500KM，通行 300KM；中通和沙特应用推进中；robotaxi 0530：乘客hmi发布前场；日志片段打包上传功能发布前场；按周统计接管原因和bug分类；车端功能持续优化",
              prop_key: "status_info",
              username: "姜岩",
              avatar:
                "https://s3-imfile.feishucdn.com/static-resource/v1/f1546616-8246-4e63-ae51-a9d1dd4242ag~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-06-01 14:15:54",
              value:
                "小U安全MPI 500KM，通行 300KM；中通和沙特应用推进中；robotaxi 0530：乘客hmi发布前场；日志片段打包上传功能发布前场；按周统计接管原因和bug分类；车端功能持续优化",
              jd_id: 9722,
              old_value:
                "小U安全MPI 500KM，通行 300KM；中通和沙特应用推进中；乘客hmi开发内场测试完成；车端功能持续优化，解决高架下lslam定位功能，持续扩展路线；洛书从日志自动分析隐患和性能上线",
              prop_key: "status_info",
              username: "姜岩",
              avatar:
                "https://s3-imfile.feishucdn.com/static-resource/v1/f1546616-8246-4e63-ae51-a9d1dd4242ag~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-05-31 10:46:46",
              value:
                "小U安全MPI 500KM，通行 300KM；中通和沙特应用推进中；乘客hmi开发内场测试完成；车端功能持续优化，解决高架下lslam定位功能，持续扩展路线；洛书从日志自动分析隐患和性能上线",
              jd_id: 9242,
              old_value:
                "小U安全MPI 500KM，通行 300KM；中通和沙特已经签单；乘客hmi开发内场测试完成；车端功能持续优化，解决高架下lslam定位功能，持续扩展路线；洛书从日志自动分析隐患和性能上线",
              prop_key: "status_info",
              username: "彭进展",
              avatar:
                "https://s1-imfile.feishucdn.com/static-resource/v1/884a297b-63fa-4b01-b21b-6b9736fde99g~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-05-06 13:44:41",
              value:
                "小U安全MPI 500KM，通行 300KM；中通和沙特已经签单；乘客hmi开发内场测试完成；车端功能持续优化，解决高架下lslam定位功能，持续扩展路线；洛书从日志自动分析隐患和性能上线",
              jd_id: 8460,
              old_value:
                "小U安全MPI 500KM，通行 300KM；中通和沙特已经签单；乘客hmi开发内场测试完成；车端功能持续优化；洛书从日志自动分析隐患和性能上线",
              prop_key: "status_info",
              username: "姜岩",
              avatar:
                "https://s3-imfile.feishucdn.com/static-resource/v1/f1546616-8246-4e63-ae51-a9d1dd4242ag~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-05-06 13:44:05",
              value:
                "小U安全MPI 500KM，通行 300KM；中通和沙特已经签单；乘客hmi开发内场测试完成；车端功能持续优化；洛书从日志自动分析隐患和性能上线",
              jd_id: 8459,
              old_value: "小U安全MPI 500KM，通行 300KM；中通和沙特已经签单",
              prop_key: "status_info",
              username: "姜岩",
              avatar:
                "https://s3-imfile.feishucdn.com/static-resource/v1/f1546616-8246-4e63-ae51-a9d1dd4242ag~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
            {
              id: 0,
              journaled_id: 0,
              user_id: 0,
              journaled_type: 0,
              create_time: "2021-05-06 13:13:18",
              value: "小U安全MPI 500KM，通行 300KM；中通和沙特已经签单",
              jd_id: 8437,
              old_value: "",
              prop_key: "status_info",
              username: "彭进展",
              avatar:
                "https://s1-imfile.feishucdn.com/static-resource/v1/884a297b-63fa-4b01-b21b-6b9736fde99g~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp",
            },
          ],
        },
      ],
      children: [
        {
          id: 681,
          time_cycle_id: 5,
          name: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaA",
          department: "基础平台研发",
          status: "unconsidered",
          status_info: "",
          progress: 0,
          score: 0,
          score_info: "",
          comments: "",
          parent_id: 562,
          author_id: 26,
          o_type: 1,
          is_publish: 1,
          is_delete: 0,
          is_hidden: 0,
          start_time: "2021-04-01 00:00:00",
          end_time: "2021-06-30 00:00:00",
          OwnerId: 10006,
          weightSum: 0,
          Username: "张丹",
          owners: [
            {
              id: 10006,
              name: "张丹",
            },
            {
              id: 10007,
              name: "周小成",
            },
          ],
          visitors: null,
          keyResults: null,
          children: null,
          parent: null,
          stutusInfoHistories: null,
        },
        {
          id: 683,
          time_cycle_id: 5,
          name: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
          department: "基础平台研发",
          status: "unconsidered",
          status_info: "",
          progress: 0,
          score: 0,
          score_info: "",
          comments: "",
          parent_id: 562,
          author_id: 26,
          o_type: 1,
          is_publish: 1,
          is_delete: 0,
          is_hidden: 0,
          start_time: "2021-04-01 00:00:00",
          end_time: "2021-06-30 00:00:00",
          OwnerId: 10006,
          weightSum: 0,
          Username: "张丹",
          owners: [
            {
              id: 10006,
              name: "张丹",
            },
            {
              id: 10007,
              name: "周小成",
            },
          ],
          visitors: null,
          keyResults: null,
          children: null,
          parent: null,
          stutusInfoHistories: null,
        },
        {
          id: 684,
          time_cycle_id: 5,
          name: "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY",
          department: "基础平台研发",
          status: "unconsidered",
          status_info: "",
          progress: 0,
          score: 0,
          score_info: "",
          comments: "",
          parent_id: 562,
          author_id: 26,
          o_type: 1,
          is_publish: 1,
          is_delete: 0,
          is_hidden: 0,
          start_time: "2021-04-01 00:00:00",
          end_time: "2021-06-30 00:00:00",
          OwnerId: 10030,
          weightSum: 0,
          Username: "蔡尧",
          owners: [
            {
              id: 10030,
              name: "蔡尧",
            },
          ],
          visitors: null,
          keyResults: null,
          children: null,
          parent: null,
          stutusInfoHistories: null,
        },
      ],
      parent: null,
      stutusInfoHistories: null,
    },
  ]);

  return (
    <div
      style={{
        width: "100%",
        height: "100%",
      }}
    >
      <OkrTree dataSource={listData} />
    </div>
  );
}

const container = document.getElementById("root");
ReactDOM.render(<App />, container);

/**
 * concurrent 模式： ReactDOM.createRoot(rootNode).render(<App />)
 */
// ReactDOM.createRoot(document.getElementById("root")).render(<App />);
